### ISSUE TITLE
Техническое задание

### ISSUE THREAD

**Issue by EkaterinaSazonova** [EkaterinaSazonova/scaling-octo-engine#3]
**1. Техническое задание**

**1.1. Общие сведения**
1.1.1. Наименование системы:
Мобильное приложение в помощь рукодельницам
1.1.2. Наименование организации заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н.Э. Баумана
Разработчик: Студентка группы ИУК5-51Б КФ МГТУ им. Н.Э. Баумана Сазонова Екатерина Владимировна.
1.1.3. Плановые сроки:
Начало работы: 01.09.2023;
Окончание работы: 31.12.2023.

**1.2. Назначение и цели создания (развития) системы**
1.2.1. Назначение системы
Система предназначена для обладателей мобильных устройств на операционной системе Android и направлена на аудиторию людей, увлекающихся вязанием, предоставляя различные мастер-классы, публикации других пользователей и возможность общения с другими рукодельницами.
1.2.2. Цели создания системы
Система создаётся с целью помочь начинающим рукодельницам научиться вязать спицами или крючком, приобрести новые навыки уже умелым мастерицам, или найти вдохновение на создание своих изделий.

**1.3. Характеристика объектов автоматизации**
Объектом автоматизации является процесс подбора информации и материалов по интересам пользователя, публикация выложенных на профиле пользователя материалов.

**1.4. Требования к системе**
1.4.1. Требования к системе в целом
Решения, отражённые в архитектуре мобильного приложения, должны обеспечивать построение приложения, соответствующей следующим принципам:
•	Система должна быть интуитивно понятной и простой для простых пользователей, чтобы её освоение занимало малое количество времени и наиболее полное и продуктивное использование системы.
•	Система должна быть надёжной и безопасной, обеспечивать конфиденциальность данных пользователей.
•	Система должна быть экономичной, не требуя больших ресурсов в процессе функционирования.
•	Система должна быть функционально расширяемой, имея возможность ввода дополнительных функциональных возможностей, не предусмотренных в техническом задании.
1.4.2. Требования к функциям (задачам), выполняемым системой:
•	Обеспечение пользователей учебным и дополнительным материалом по рукоделию.
•	Предоставление пользователям возможности контакта путём общения в чатах.
•	Предоставление возможности публикации своих материалов для общего доступа.
1.4.3. Требования к видам обеспечения:
•	Данные будут храниться и обрабатываться системой управления базами данных (СУБД). Например: MySQL, PostgreSQL, MongoDB.
•	Система разрабатывается для мобильного устройства, которое должно иметь доступ в сеть интернет.

**1.5. Состав и содержание работ по созданию системы**
Этапы работ:
1 этап (1 – 4-я недели) – утверждение темы, техническое задание, описание предметной области и требований к системе. Концептуальная схема данных.
2 этап (5 – 7-я недели) – прототип или скетчи пользовательского интерфейса, оформление введения и исследовательской части. Выбор БД, логическая БД, физическая БД, разработка и демонстрация макета системы с БД.
3 этап (8 – 10-я недели) – проектно-конструкторская часть. Тестирование и отладка приложения. Разработка эксплуатационной документации.
4 этап (11 – 14-я недели) – завершающее оформление документации согласно требованиям ГОСТ. Подготовка доклада, защита курсовой работы.

**1.6. Порядок контроля и приемки системы**
Установить контроль и приёмку результатов работ на каждый стадии создания системы в соответствии с разделом 1.5.
По окончании работы предъявляется расчётно-пояснительная записка, в состав которой входят:
•	Техническое задание
•	Научно-исследовательская часть
•	Проектно-конструкторская часть
•	Проектно-технологическая часть
Приёмка работы, осуществляемая комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5, сопровождается проверкой соответствия системы требованиям, описанным в техническом задании.

**1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие:**
•	Настройка сервера для обеспечения безопасности и корректности функционирования системы;
•	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в техническом задании.

**1.8. Требования к документированию**
Разработку системы требуется сопровождать расчётно-пояснительной запиской и графической частью. Расчётно-пояснительная записка состоит из следующих частей:
•	Техническое задание в соответствии с ГОСТ 34.602-89
•	Научно-исследовательская часть
•	Проектно-конструкторская часть
•	Проектно-технологическая часть

**1.9. Источники разработки**
При составлении технического задания были использованы следующая литература и нормативные документы:
•	ГОСТ 34.602-89 «Техническое задание на создание автоматизированной системы»;
•	ГОСТ 34.601-90 «Информационная технология. Комплекс стандартов на автоматизированные системы. Стадии создания».

**Comment by wldmr-key** [comment]
Цели - благотворительность? Кто за все это может заплатить?

Пока весьма неочевидна достаточность сложности проекта для курсовой работы - навскидку сколько сущностей ты видишь?
будет ли осуществляться поддержка? Есть для этого функции?

**Comment by EkaterinaSazonova** [comment]
Сущностей у меня будет 7, я почти оформила концептуальную схему.
В плане монетизации, в приложении будут выкладываться мастер-классы, большая часть которых будет платной. Также приложение может со временем обновляться, и можно будет добавить какие-то удобные функции, за которые надо будет платить условную сумму. + не исключается возможность размещения неназойливой рекламы.

**Comment by wldmr-key** [comment]
ну так переформулируй цели и назначение!

**Comment by EkaterinaSazonova** [comment]
**1. Техническое задание**
1.1. Общие сведения
1.1.1. Наименование системы:
Чат бот для рукоделия
1.1.2. Наименование организации заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н.Э. Баумана
Разработчик: Студентка группы ИУК5-51Б КФ МГТУ им. Н.Э. Баумана Сазонова Екатерина Владимировна.
1.1.3. Плановые сроки:
Начало работы: 01.09.2023;
Окончание работы: 31.12.2023.

1.2. Назначение и цели создания (развития) системы
1.2.1. Назначение системы
Система предназначена для пользователей мессенджера Telegram и направлена на аудиторию увлекающихся вязанием и плетением людей, предоставляя возможность простого доступа к нужным материалам, приобрести которые пользователи могут бесплатно или за установленную автором материала цену.
1.2.2. Цели создания системы
Целью создания системы является упрощение доступа к нужному материалу людей, которые интересуются такими видами рукоделия как вязание и плетение. 

1.3. Характеристика объектов автоматизации
Объектом автоматизации является процесс поиска информации и материалов по запросам пользователя, публикация материалов.

1.4. Требования к системе
1.4.1. Требования к системе в целом
•	Система должна быть интуитивно понятной и простой для простых пользователей, чтобы её освоение занимало малое количество времени и наиболее полное и продуктивное использование системы.
•	Система должна быть надёжной и безопасной, обеспечивать конфиденциальность данных пользователей.
•	Система должна быть экономичной, не требуя больших ресурсов в процессе функционирования.
•	Система должна быть функционально расширяемой, имея возможность ввода дополнительных функциональных возможностей, не предусмотренных в техническом задании.
1.4.2. Требования к функциям (задачам), выполняемым системой:
•	Обеспечение пользователей учебным и дополнительным материалом по рукоделию.
•	Предоставление пользователям возможности контакта путём переписки или аудио-звонков.
•	Предоставление возможности публикации своих материалов для общего доступа.
1.4.3. Требования к видам обеспечения:
•	Хранение и обработка данных системой управления базами данных (СУБД). Например: MySQL, PostgreSQL, MongoDB.
•	Система разрабатывается для мессенджера Telegram, которое должно иметь доступ в сеть интернет.

1.5. Состав и содержание работ по созданию системы
Этапы работ:
1 этап (1 – 4-я недели) – утверждение темы, техническое задание, описание предметной области и требований к системе. Концептуальная схема данных.
2 этап (5 – 7-я недели) – прототип или скетчи пользовательского интерфейса, оформление введения и исследовательской части. Выбор БД, логическая БД, физическая БД, разработка и демонстрация макета системы с БД.
3 этап (8 – 10-я недели) – проектно-конструкторская часть. Тестирование и отладка приложения. Разработка эксплуатационной документации.
4 этап (11 – 14-я недели) – завершающее оформление документации согласно требованиям ГОСТ. Подготовка доклада, защита курсовой работы.

1.6. Порядок контроля и приемки системы
Установить контроль и приёмку результатов работ на каждый стадии создания системы в соответствии с разделом 1.5.
По окончании работы предъявляется расчётно-пояснительная записка, в состав которой входят:
•	Техническое задание
•	Научно-исследовательская часть
•	Проектно-конструкторская часть
•	Проектно-технологическая часть
Приёмка работы, осуществляемая комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5, сопровождается проверкой соответствия системы требованиям, описанным в техническом задании.

1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие:
•	Настройка сервера для обеспечения безопасности и корректности функционирования системы;
•	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в техническом задании.

1.8. Требования к документированию
	Разработку системы требуется сопровождать расчётно-пояснительной запиской и графической частью. Расчётно-пояснительная записка состоит из следующих частей:
•	Техническое задание в соответствии с ГОСТ 34.602-89
•	Научно-исследовательская часть
•	Проектно-конструкторская часть
•	Проектно-технологическая часть

1.9. Источники разработки
При составлении технического задания были использованы следующая литература и нормативные документы:
•	ГОСТ 34.602-89 «Техническое задание на создание автоматизированной системы»;
•	ГОСТ 34.601-90 «Информационная технология. Комплекс стандартов на автоматизированные системы. Стадии создания».

**Comment by wldmr-key** [comment]
цель - по-прежнему, как я вижу, благотворительность
в функциональных задачах, по-прежнему, не вижу 7 сущностей. Может, перечислишь?

**Comment by EkaterinaSazonova** [comment]
Я решила вернуться к начальной идее с чат ботом, поэтому сущностей теперь будет 5-6, концептуальную схему и описание предметной области я переделаю.
А что касается цели, я никак не могу сообразить, как мне её написать, чтобы это не выглядело как чистая благотворительность.
Можно ли написать вот так:
Целью создания системы является упрощение доступа к нужному материалу людей, которые интересуются такими видами рукоделия как вязание и плетение, предоставляя как платный, так и бесплатный контент.

**Comment by wldmr-key** [comment]
у тебя уже целью является благотворительность. То есть, сервис создается ради того, чтобы мир стал лучше, как я понимаю ))

**Comment by EkaterinaSazonova** [comment]
**1. Техническое задание**

**1.1. Общие сведения**
1.1.1. Наименование системы:
Чат бот для рукодельниц
1.1.2. Наименование организации заказчика, разработчика системы:
Заказчик: КФ МГТУ им. Н.Э. Баумана
Разработчик: Студентка группы ИУК5-51Б КФ МГТУ им. Н.Э. Баумана Сазонова Екатерина Владимировна.
1.1.3. Плановые сроки:
Начало работы: 01.09.2023;
Окончание работы: 31.12.2023.

**1.2. Назначение и цели создания (развития) системы**
1.2.1. Назначение системы
Система предназначена для пользователей мессенджера Telegram и направлена на аудиторию увлекающихся вязанием и плетением людей, предоставляя возможность простого доступа к нужным материалам, приобрести которые пользователи могут бесплатно или за установленную автором материала цену.
1.2.2. Цели создания системы
Бот помогает найти, выбрать и приобрести материал и инструкции по созданию вязаных и плетёных изделий, а также найти людей с такими же интересами и связаться с ними. 

**1.3. Характеристика объектов автоматизации**
Объектом автоматизации является процесс поиска информации и материалов по запросам пользователя, публикация материалов.

**1.4. Требования к системе**
1.4.1. Требования к системе в целом
•	Система должна быть интуитивно понятной и простой для простых пользователей, чтобы её освоение занимало малое количество времени и наиболее полное и продуктивное использование системы.
•	Система должна быть надёжной и безопасной, обеспечивать конфиденциальность данных пользователей.
•	Система должна быть экономичной, не требуя больших ресурсов в процессе функционирования.
•	Система должна быть функционально расширяемой, имея возможность ввода дополнительных функциональных возможностей, не предусмотренных в техническом задании.
1.4.2. Требования к функциям (задачам), выполняемым системой:
•	Обеспечение пользователей учебным и дополнительным материалом по рукоделию.
•	Предоставление пользователям возможности контакта путём переписки или аудио-звонков.
•	Предоставление возможности публикации своих материалов для общего доступа.
1.4.3. Требования к видам обеспечения:
•	Хранение и обработка данных системой управления базами данных (СУБД). Например: MySQL, PostgreSQL, MongoDB.
•	Система разрабатывается для мессенджера Telegram, которое должно иметь доступ в сеть интернет.

**1.5. Состав и содержание работ по созданию системы**
Этапы работ:
1 этап (1 – 4-я недели) – утверждение темы, техническое задание, описание предметной области и требований к системе. Концептуальная схема данных.
2 этап (5 – 7-я недели) – прототип или скетчи пользовательского интерфейса, оформление введения и исследовательской части. Выбор БД, логическая БД, физическая БД, разработка и демонстрация макета системы с БД.
3 этап (8 – 10-я недели) – проектно-конструкторская часть. Тестирование и отладка приложения. Разработка эксплуатационной документации.
4 этап (11 – 14-я недели) – завершающее оформление документации согласно требованиям ГОСТ. Подготовка доклада, защита курсовой работы.

**1.6. Порядок контроля и приемки системы**
Установить контроль и приёмку результатов работ на каждый стадии создания системы в соответствии с разделом 1.5.
По окончании работы предъявляется расчётно-пояснительная записка, в состав которой входят:
•	Техническое задание
•	Научно-исследовательская часть
•	Проектно-конструкторская часть
•	Проектно-технологическая часть
Приёмка работы, осуществляемая комиссией КФ МГТУ им. Н.Э. Баумана кафедры ИУК5, сопровождается проверкой соответствия системы требованиям, описанным в техническом задании.

**1.7. Требования к составу и содержанию работ по подготовке объекта автоматизации к вводу системы в действие:**
•	Настройка сервера для обеспечения безопасности и корректности функционирования системы;
•	Создание условий функционирования объекта автоматизации, при которых гарантируется соответствие создаваемой системы требованиям, содержащимся в техническом задании.

**1.8. Требования к документированию**
	Разработку системы требуется сопровождать расчётно-пояснительной запиской и графической частью. Расчётно-пояснительная записка состоит из следующих частей:
•	Техническое задание в соответствии с ГОСТ 34.602-89
•	Научно-исследовательская часть
•	Проектно-конструкторская часть
•	Проектно-технологическая часть

**1.9. Источники разработки**
При составлении технического задания были использованы следующая литература и нормативные документы:
•	ГОСТ 34.602-89 «Техническое задание на создание автоматизированной системы»;
•	ГОСТ 34.601-90 «Информационная технология. Комплекс стандартов на автоматизированные системы. Стадии создания».

**Comment by EkaterinaSazonova** [comment]
Сделать мир лучше у меня возможности нет), поэтому надеюсь, что в этот раз цель корректнее указана

**Comment by wldmr-key** [comment]
> Сделать мир лучше у меня возможности нет), поэтому надеюсь, что в этот раз цель корректнее указана

ошибаешься по обоим пунктам. Но оставляй, уж, так
