### ISSUE TITLE
Описание предметной области

### ISSUE THREAD

**Issue by EkaterinaSazonova** [EkaterinaSazonova/scaling-octo-engine#4]
**Мобильное приложение для рукодельниц**

Требуется разработать систему мобильного приложения, на котором люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями приложения.

Каждый пользователь при регистрации в приложении должен указать никнейм, номер телефона, адрес электронной почты (можно что-то одно), и по желанию прикрепить изображение в качестве аватара.

Пользователи могут выкладывать публикации в виде текста, изображений или видео, у которых отображаются название, содержание и дата публикации.

К публикации можно оставить комментарий, у которого также отображаются содержание и дата добавления.

В чатах пользователи смогут связаться с друг другом. У каждого чата указываются название, аватар чата и количество участников.

У сообщений в чатах отображаются содержание, дата отправления и статус сообщения.

К сообщению или публикации можно оставить реакцию, которая выглядит как символ: смайлик или стике.

В разделе мастер-классов пользователи могут найти материал как для обучения, так и уже требующий каких-то навыков для создания какого-то изделия. Для мастер-классов должны указываться тема, название и формат (т.е. презентация это или текстовый документ). Сами мастер-классы выкладываются самими пользователями, и могут быть как платные, так и бесплатные.

**Comment by wldmr-key** [comment]
жду переделки для бота

**Comment by EkaterinaSazonova** [comment]
**Telegram бот для рукоделия**

Требуется разработать систему чат бота для мессенджера Telegram, с помощью которого люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями бота.

У каждого **пользователя** должны быть указаны _имя_, _фамилия_ (необязательно), _номер телефона_, _имя пользователя_, и по желанию можно прикрепить изображение в качестве _аватара_.

**Пользователи** могут выкладывать **публикации** в виде текста, изображений или видео, у которых отображаются _название_, _содержание_ и дата _публикации_.

Через **сообщения** **пользователи** могут переписываться друг с другом и писать запросы боту. У **сообщений** отображаются _содержание_, _дата отправления_ и _статус сообщения_.

К **сообщению** или **публикации** можно оставить **реакцию**, которая выглядит как _символ_: смайлик или стикер.

Через **сообщение** **пользователь** может запросить у бота, найти **мастер-класс** для создания того или иного изделия. Для **мастер-классов** должны указываться _тема_, _название_, _формат_ (т.е. презентация это или текстовый документ) и _цена_ (платный или бесплатный), которую указывает автор мастер-класса.

**Comment by EkaterinaSazonova** [comment]
**Telegram бот для рукоделия**

Требуется разработать систему чат бота для мессенджера Telegram, с помощью которого люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями бота.

У каждого **пользователя** должны быть указаны _имя_, _фамилия_ (необязательно), _номер телефона_, _имя пользователя_, и по желанию прикрепить изображение в качестве _аватара_.

**Пользователи** могут выкладывать **публикации** в виде текста, изображений или видео, у которых отображаются _название_, _содержание_ и _дата публикации_.

Через **сообщения** **пользователи** могут переписываться друг с другом и писать запросы боту. У **сообщений** отображаются _содержание_, _дата отправления_ и _статус сообщения_.

К **сообщению** или **публикации** можно оставить **реакцию**, которая выглядит как _символ_: смайлик или стикер.

Через **сообщение** **пользователь** может запросить у бота, найти **мастер-класс** для создания того или иного изделия. Для **мастер-классов** должны указываются _тема_, _название_, _формат_ (т.е. презентация это или текстовый документ) и _цена_ (платный или бесплатный), которую указывает автор **мастер-класса**.

**Comment by wldmr-key** [comment]
пусть будет так. Вопрос - сообщения друг-другу пользователи разве пишут не средствами телеграма? Чаты, разве, не телеграммные? Ты их держишь в своем приложении? Реально?
Как это будет реализовываться средствами бота? не очень представляю

**Comment by EkaterinaSazonova** [comment]
**Telegram бот для рукоделия**

Требуется разработать систему чат бота для мессенджера Telegram, с помощью которого люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями бота.

У каждого **пользователя** должны быть указаны _никнейм_ и _адрес электронной почты_.

Пользователи могут выкладывать **публикации** в виде текста, изображений или видео, у которых отображаются _название_, _содержание_ и _дата публикации_.

Также пользователь может сделать **заказ**, у которого указываются _название_, _категория заказа_, исполнителем устанавливается цена, и отображается _статус заказа_.

Пользователь может запросить у бота, найти **мастер-класс** для создания того или иного изделия. Для **мастер-классов** должны указываться _тема_, _название_, _формат_ (т.е. презентация это или текстовый документ) и _цена_, которую указывает автор мастер-класса.

Кроме того, пользователь может добавить бесплатный мастер-класс или любую другую публикацию в **избранные**, которые можно просмотреть, обратившись к боту. Для **избранных** обязательно указываются _название_ и _категория_.

**Comment by wldmr-key** [comment]
все приемлемо, кроме заказов. Подробнее написал в https://github.com/EkaterinaSazonova/scaling-octo-engine/issues/5

**Comment by EkaterinaSazonova** [comment]
Да, с Заказами я напутала, всё наоборот сделала

**Comment by EkaterinaSazonova** [comment]
**Telegram бот для рукоделия**

Требуется разработать систему чат бота для мессенджера Telegram, с помощью которого люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями бота.

У каждого **пользователя** должны быть указаны _никнейм_ и _адрес электронной почты_.

**Пользователи** могут выкладывать **публикации** в виде текста, изображений или видео, у которых отображаются _название_, _содержание_ и _дата публикации_.

Также **пользователь** может приобрести **товар**, то есть готовое изделие, исполнитель которого указывает его _название_, _категорию_ и _цену_.

**Пользователь** может запросить у бота, найти **мастер-класс** для создания того или иного изделия. Для **мастер-классов** должны указываться _тема_, _название_, _формат_ (т.е. презентация это или текстовый документ) и _цена_, которую указывает автор **мастер-класса**.

Кроме того, **пользователь** может добавить бесплатный мастер-класс или любую другую публикацию в **избранные**, которые можно просмотреть, обратившись к боту. Для **избранных** обязательно указываются _название_ и _категория_.

**Comment by EkaterinaSazonova** [comment]
Я ничего дельного с заказами не придумала, поэтому, просмотрев несколько сообществ рукодельниц в vk, я решила их переделать в **товары**.

**Comment by wldmr-key** [comment]
и, да ладно! Код, давай!

**Comment by EkaterinaSazonova** [comment]
Я опять переделала описание предметной области. Может быть получше предыдущего варианта. А разработку я начала


**Telegram бот для рукоделия**

Требуется разработать систему чат бота для мессенджера Telegram, с помощью которого люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями бота.

У каждого **пользователя** должны быть указан _никнейм_.

**Пользователи** могут выкладывать **публикации** в виде текста, изображений или видео, у которых отображаются _название_, _содержание_ и _дата публикации_.

Также **пользователь** может в разделе **товаров** продать своё изделие или приобрести, то есть готовая вещь, для которой указаны _название_, _категория_ и _цена_. 

**Пользователь** может запросить у бота, найти **мастер-класс** для создания того или иного изделия. Для **мастер-классов** должны указываться _тема_, _название_, _формат_ (т.е. презентация это или текстовый документ) и _цена_, которую указывает автор мастер-класса.

Кроме того, **пользователь** может добавить **товар** или **публикацию** в **избранные**, которые можно просмотреть, обратившись к боту. Для избранных обязательно указываются _название_ и _категория_.

**Comment by wldmr-key** [comment]
более корректно сказать, наверное, будет не продать, а предложить к продаже и не приобрести, а найти, так как продаж (обмена товара на деньги) твой бот, как я понимаю, не осуществляет. Так же, скорее всего, продавцу нужно иметь возможность снять купленный товар с продажи

**Comment by EkaterinaSazonova** [comment]
Я постаралась учесть ваши замечания и опять исправила описание предметной области)

**Telegram бот "Клубочек" для вязания крючком и спицами**

Требуется разработать систему чат бота для мессенджера Telegram, с помощью которого люди, увлекающиеся вязанием, могут найти материал для обучения, мастер-классы по разным изделиям, поделиться собственным опытом и успехами, а также связаться с другими пользователями бота.

У каждого **пользователя** должны быть указан _никнейм_, который будет его инициализировать как пользователя этого бота.

Пользователи могут выкладывать **публикации** в виде текста, изображений или видео, у которых отображаются _название_, _содержание_ и _дата публикации_.

Также пользователь может в разделе **товаров** предложить к продаже своё изделие или приобрести готовое у его исполнителя (такого же пользователя), который указывает _название_, _категорию_ и _цену_ предложенного **товара**.

Пользователь может запросить у бота, найти **мастер-класс** для создания того или иного изделия. Для **мастер-классов** должны указываться _тема_, _название_, _формат_ (т.е. презентация это или текстовый документ) и _цена_, которую указывает автор **мастер-класса**.

Кроме того, пользователь может добавить товар или публикацию в **избранные**, которые можно просмотреть, обратившись к боту. Для **избранных** обязательно указываются _название_ и _категория_.

**Comment by wldmr-key** [comment]
приобрести (купить) все-таки у бота можно?

**Comment by EkaterinaSazonova** [comment]
Не совсем. Я задумывала, что с помощью бота в разделе "Товаров" будут размещаться объявления о том, что продаётся такое-то изделие и по такой-то цене, а покупать пользователь уже будет у хозяина изделия, уже без бота. Возможно, оплата покупки будет проходить через бота, но это я ещё окончательно не решила

**Comment by wldmr-key** [comment]
с ботом не купишь. Поэтому, лучше писать не "приобрести", а "найти"

**Comment by EkaterinaSazonova** [comment]
Я постаралась учесть ваши замечания и исправить ошибки. Новая версия описания предметной области:

### Telegram бот для рукоделия

У некоторых людей нет возможности устроиться на обычную работу, и они вынуждены сидеть дома, поэтому они начинают искать другой способ самореализации и заработка. Один из них – это рукоделие. Создавать своими руками можно всё, что угодно, тем более всегда были, есть и будут люди, которые хотят приобрести или подарить уникальную вещь ручной работы.

В наши дни данная сфера только развивается, поэтому хороших приложений пока мало, как и сообществ для рукодельниц. Поэтому целью работы стала разработка чат бота в мессенджере Telegram для тех, кто занимается вязанием спицами и крючком, или просто хочет приобрести вязанное изделие ручной работы.

При активации бот получает **имя пользователя Telegram** и дополнительно спрашивает у пользователя **никнейм**, по которому к нему будет обращаться бот и другие пользователи системы.

 После запуска предоставляется меню, где пользователь может выбрать один из пунктов: **мастер-классы** или **товары**.

В разделе **мастер-классов** **пользователь** снова выбирает один из пунктов: поделиться или найти. В первом случае **пользователь** может поделиться собственным **мастер-классом**, указав для него _тематику_, _название_, дав ему _краткое описание_ и соответственно прикрепив сам _файл_.

Во втором случае, выбрав пункт "найти", **пользователь** выбирает **тематику мастер-класса**, и уже по этому критерию ему предоставляется список **мастер-классов**, которые можно скачать из системы.

В разделе **товаров** **пользователь** может найти интересующее его готовое изделие или выложить объявление о продаже своего рукоделия.

Чтобы найти нужный **товар** **пользователь** должен перейти по пункту «купить», а после выбрать **категорию товара**. Далее **пользователю** предоставляется список изделий, для которых указаны: _название_, _изображение_, _описание_ и _цена_ изделия. Когда **пользователь** нажимает на кнопку "купить", он получает ссылку на автора изделия. Для приобретения **товара**, **пользователь** напрямую связывается и договаривается с автором изделия.

Чтобы выставить на продажу собственный **товар**, **пользователь** должен перейти по пункту "разместить объявление", после чего он указывает **категорию товара**, _название_, _изображение_, _цену_,  и даёт небольшое _описание_. Далее бот добавляет это объявление к остальным. Также **пользователь** может убрать своё объявление.

**Comment by wldmr-key** [comment]
пойдет
