### ISSUE TITLE
Концептуальная схема данных

### ISSUE THREAD

**Issue by EkaterinaSazonova** [EkaterinaSazonova/scaling-octo-engine#5]
![Концептуальная схема](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/fc621a51-820f-4fe4-b005-eede50d23725)

**Comment by wldmr-key** [comment]
Екатерина, очень неправильно с точки зрения коллективной работы в начале создавать пустую задачу (issue), а потом ее редактировать. В этом случае я не получаю уведомлений и, как следствие, не реагирую. Нужно создавать новые комментарии, тогда я обращу внимание

что касается схемы, то, разве аватар, никнейм и номер телефона не поставляются телегой? Или у тебя они будут свои?

Чаты и лайки - это не чаты и лайки телеги?

**Comment by EkaterinaSazonova** [comment]
Прошу прощения, ошибка с пустыми задачами будет учтена.

Для бота я сделала немного другую схему. Я была не уверена, можно ли делать связь **реакций** и с **публикациями**, и с **сообщениями**.

Подразумевается, что аватар, имя и номер телефона указываются автоматически, так как у пользователя уже есть аккаунт в Telegram. И с реакциями также. Или это неправильно? Надо указывать только то, что разрабатывается в системе?

**Comment by EkaterinaSazonova** [comment]
Концептуальная схема для бота

![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/73462495-121f-4b49-82a8-ac4564990fb5)

**Comment by wldmr-key** [comment]
Насколько я понимаю, Пользователи, Сообщения и Реакции на сообщения существуют в телеге и без твоего участия и ты на них никак в своей системе не влияешь. В итоге у тебя остается база из двух-трех сущностей. Я не прав?

**Comment by EkaterinaSazonova** [comment]
![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/46af3374-bacb-4ea1-8bfe-6a59283cb526)
Я переделала немного концептуальную схему, убрала Сообщения и Реакции. Как вы сказали, у меня оставалось 3 сущности, и то Пользователи были под вопросом, поэтому добавила Заказы и Сохранённые, а у Пользователей указала атрибуты, которые будут их идентифицировать именно как пользователей этого бота

**Comment by wldmr-key** [comment]
увы, не могу оценить качества схемы без изменений в описании предметной области. Нужно дополнить. Но уже сейчас выглядит странным, что с заказом связан только один пользователь - это заказчик? Он у сайта заказывает?

**Comment by EkaterinaSazonova** [comment]
Про предметную область я благополучно забыла, переделаю. А в плане заказов я рассуждала, что пользователь может быть как заказчиком, так и выполнять заказ. В первом случае, у заказчика же может быть много заказов, а во втором случае один пользователь может выполнить много заказов. Запрос на заказ отправляется боту, а он предлагает кандидатуры исполнителей, и пользователь выбирает одного из них.

**Comment by EkaterinaSazonova** [comment]
![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/0c4bbb1f-1708-472c-b206-78dd17384b05)

Я заменила Сохранённые на Избранные, и подумала над Заказами. Не исключено то, что заказчик даст один и тот же заказ нескольким мастерицам. Но я не уверена, что связь МxN допустима. Или в этом нет ничего плохого?

**Comment by wldmr-key** [comment]
Думаю, здесь ты ошиблась с сущностями. Исполнитель (потенциальный) каких-либо работ готовит предложение, на которое могут откликнуться, а могут не откликнуться заказчики. 

И, кстати, как будет выглядеть поиск среди предложений? Пример

**Comment by EkaterinaSazonova** [comment]
Да, с Заказами я напортачила. Логичнее, как вы сказали. На счёт поиска предложений я уже не уверена, поэтому переделаю так, что исполнитель будет предлагать свои изделия, а покупатели/заказчики могут или приобрести этот товар, или заказать у этого мастера что-то ещё.

**Comment by EkaterinaSazonova** [comment]
Изменённая концептуальная схема, в соответствии с последней версией описания предметной области:
![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/7cc9f1b8-65dc-44b9-80ea-56c0fdd43a1d)

**Comment by wldmr-key** [comment]
не очень объяснима связь M:N между пользователями и товарами
"Избранное" разве свяязано только с пользователем? А что он избрал?

**Comment by EkaterinaSazonova** [comment]
Я подумала над связью между пользователями и товарами, и решила её сделать 1:М. А "Избранное" всё таки связано с товарами и публикациями, а не напрямую с пользователем

![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/73b4e4b6-cd45-4391-9bdf-b438cbc0811c)

**Comment by wldmr-key** [comment]
> А "Избранное" всё таки связано с товарами и публикациями, а не напрямую с пользователем

и кем же, тогда они избраны? ))

**Comment by EkaterinaSazonova** [comment]
Ой, ну да. Но тогда совсем лес из связей выходит. Я не уверена, что так можно, но по моей задумке получается так:

![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/1dfc5f82-f389-4139-844b-a419fabe91d2)

**Comment by wldmr-key** [comment]
нормально, только у избранного название (и категория), разве, отличается от названия товара/ мастер-класса?
И целесообразна ли одна сущность, а не две - избранные товары, избранные мастер-классы?

**Comment by EkaterinaSazonova** [comment]
Новая версия концептуальной схемы

![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/7a26d0f1-bbef-45ef-8b06-c89ee4c810f2)

**Comment by wldmr-key** [comment]
никнейм автора в товаре лишний - он определяется связью

**Comment by wldmr-key** [comment]
И, неужели, информация об авторе разная в разных мастер-классах?

**Comment by EkaterinaSazonova** [comment]
Да, с авторами я переборщила. Поэтому я убрала автора в мастер-классах и никнейм автора в товарах. Как вы сказали, никнеймы пользователей (авторов) будут определяться связями в логической схеме.

![image](https://github.com/EkaterinaSazonova/scaling-octo-engine/assets/144559919/79f4f9fd-63af-4c7e-b889-6aa2d05df502)
